config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'articles#index'
  get '/xml', to: 'articles#xml'
  get '/json', to: 'articles#json'
  get '/misc', to: 'misc#misc'
  get '/articles_category/:category_id', to: 'articles#articles_by_category'
  # resource :books
  resources :articles do
    resources :comments
  end

  resources :categories do
    resources :comments
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class TestingValidator < ActiveModel::Validator
  def validate(record)
    if record.title == "Testing"
      record.errors.add :base, "This is Testing Article"
    end
  end
end
class Article < ApplicationRecord
  belongs_to :category
  has_many :comments, as: :commentable

  before_save do
    self.title = title.upcase
  end


  validates :title, length: { minimum: 5, message: 'Length must be greater than 5 characters' }
  validates :body, length: { minimum: 10, message: 'content must be greater than 10 characters' }
  validates :title, uniqueness: { message: ' Already exists' }
  validates_with TestingValidator
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :articles, dependent: :destroy
  has_many :comments, as: :commentable
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/models/photo.rb
# frozen_string_literal: true

class Photo < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  layout 'application'
  rescue_from ActiveRecord::RecordNotFound do |_exception|
    no_record_url
  end

  def no_record_url
    render '/not_found'
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

 skip_before_action :verify_authenticity_token, :only => [:destroy]
  def index
    @articles=Article.all
  end


  def show
    @article = Article.find(params[:id])
    @commentable = @article
    @comments = @commentable.comments
    @comment = Comment.new
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    # redirect_to root_path, status: :see_other
  end

  def xml
    @article=Article.find(3)
    render xml:@article.title
  end

  def json
    @articles=Article.all
    render json:@articles
  end

  def articles_by_category
    @category=Category.find(params[:category_id])
    @articles=@category.article
    render "articles/index"
  end

  private

  def article_params
    params.require(:article).permit(:title,:body,:category_id)
  end


end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
    @commentable = @category
    @comments = @commentable.comments
    @comment = Comment.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to @category
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to root_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :load_commentable

  def index
    @comments = @commentable.comments
  end

  def new
    @comment = @commentable.comments.new
  end

  def create
    @comment = @commentable.comments.new(comment_params)
    if @comment.save
      redirect_to @commentable, notice: 'Comment created.'
    else
      render :new
    end
  end

  private

  def load_commentable
    resource, id = request.path.split('/')[1, 2]
    @commentable = resource.singularize.classify.constantize.find(id)
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/misc_controller.rb
# frozen_string_literal: true

class MiscController < ApplicationController
  def misc; end
end

app/controllers/photos_controller.rb
# frozen_string_literal: true

class PhotosController < ApplicationController
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/misc_helper.rb
# frozen_string_literal: true

module MiscHelper
end

app/helpers/photos_helper.rb
# frozen_string_literal: true

module PhotosHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
<div>
    <%= form.label :category_id %><br>
    <%= form.select :category_id, options_for_select(Category.all.map{|c|[c.name, c.id]})  %>
  </div>

  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>
<%# <%= debug @articles %>
<%# <%= simple_format @articles.to_yaml %>
<%# <%= [1,2,3,4].inspect %>

<p>Welcome! The date and time is <%= Time.now %></p>
<% @greeting = capture do %>
  <p>Welcome! Asad to Articles</p>
<% end %>

<%= @greeting %>

<%= link_to "New Article", new_article_path %>
<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article %>
    </li>
  <% end %>
</ul>
<%# <%= javascript_tag "alert('All is good')"
 %>
 <%= number_to_currency(1234567890.50)
 %>
 <%= number_to_human(1234567) %>

app/views/articles/new.html.erb
<h1>New Article</h1>
<div style="color:red">
<% if @article.errors.any? %>
<% @article.errors.full_messages.each do |error| %>
<div><%= error %></div>
<% end %>
<% end %>
</div>
<%= form_with model: @article do |form|%>

  <div>
    <%= form.label :category_id %><br>
    <%= form.select :category_id, options_for_select(Category.all.map{|c|[c.name, c.id]}) %>
  </div>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<h1><%= @article.category.name rescue 'No Category for this article' %></h1>
<p><%=  @article.body %></p>

<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= button_to "Destroy", article_path(@article), method: :delete %></li>
  <button id="delete">delete</button>
</ul>

<%= link_to "New Comment", [:new, @commentable, :comment] %>
<br>

<% @comments.each do |c| %>
<%= c.content %>
<br>
<% end %>



  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

<script>
  $(document).ready(function() {
   $('#delete').on('click',function(){
    id="<%= @article.id %>"
    token=$('meta[name="csrf-token"]'). attr('content')
    $.ajax({
      url:'/articles/'+id,
      method:"delete",
      headers:{
        'authenticity_token':token
      },
      success:function(data){

      }

    })
   });
  });
  </script>

app/views/categories/_form.html.erb
<%= form_with model: category  do |form| %>
 <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% category.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <%= form.submit %>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category </h1>
<%= render  "form", category: @category %>

app/views/categories/index.html.erb
<%= link_to "New Category", new_category_path  %>
<ul>
  <% @categories.each do |category| %>
    <li>
      <%= link_to category.name, category %>
    </li>
  <% end %>
</ul>

app/views/categories/new.html.erb
<div>
<%= form_with model: @category do |form| %>
 <%= form.label :name %><br>
 <%= form.text_field :name %>
 <%= form.submit %>
  </div>
<% end %>

app/views/categories/show.html.erb
<%= @category.name  %>
<li><%= link_to "Edit", edit_category_path(@category) %></li>
<li><%= button_to "Destroy", category_path(@category), method: :delete %></li>


<%= link_to "New Comment", [:new, @commentable, :comment] %>

<% @comments.each do |c| %>
<%= c.content %>
<br>
<% end %>

app/views/comments/index.html.erb
<%= link_to "New Comment", [:new, @commentable, :comment] %>

app/views/comments/new.html.erb
<%= form_for [@commentable, @comment] do |f| %>
    <%= f.label :content %><br>
    <%= f.text_area :content, rows: 8 %>
    <%= f.submit %>
<% end %>

app/views/layouts/_menu.html.erb
<h4>This is menu</h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <h1>This is header</h1>
  <%= render "layouts/menu" %>


  <body>
    <%= yield %>

  <h1>This is footer</h1>

  </body>
</html>

app/views/misc/misc.erb
<%= image_url("https://www.pexels.com/photo/city-with-high-rise-buildings-during-night-time-12491573/",host="https://www.pexels.com")
 %>